# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore src
      
    - name: Build
      run: dotnet build -c Release src --no-restore 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3

    - name: Build Migration Service Image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6
      with:
        context: src
        file: src/Ires.MigrationService/Dockerfile
        push: false
        tags: ires/migration-service:latest,ires/frontend:${{ github.run_number }}

    - name: Build Frontend Service Image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6
      with:
        context: src
        file: src/Ires.Frontend/Dockerfile
        push: false
        tags: ires/frontend:latest,ires/frontend:${{ github.run_number }}
